spring:
  mail:
    host: smtp.gmail.com
    username: vannamhd96@gmail.com
    password: adwoekvykqaalobp
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
